// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/users.proto

/*
Package users is a generated protocol buffer package.

It is generated from these files:
	proto/user/users.proto

It has these top-level messages:
	User
	UserId
	Void
	UserList
*/
package users

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id               *int64  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	FirstName        *string `protobuf:"bytes,2,req,name=firstName" json:"firstName,omitempty"`
	City             *string `protobuf:"bytes,3,req,name=city" json:"city,omitempty"`
	Phone            *string `protobuf:"bytes,4,req,name=phone" json:"phone,omitempty"`
	Height           *string `protobuf:"bytes,5,req,name=height" json:"height,omitempty"`
	Married          *bool   `protobuf:"varint,6,req,name=married" json:"married,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil && m.FirstName != nil {
		return *m.FirstName
	}
	return ""
}

func (m *User) GetCity() string {
	if m != nil && m.City != nil {
		return *m.City
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *User) GetHeight() string {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return ""
}

func (m *User) GetMarried() bool {
	if m != nil && m.Married != nil {
		return *m.Married
	}
	return false
}

type UserId struct {
	UserId           *int64 `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UserId) Reset()                    { *m = UserId{} }
func (m *UserId) String() string            { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()               {}
func (*UserId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserId) GetUserId() int64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type Void struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// User list contains a list of users
type UserList struct {
	AllUser          []*User `protobuf:"bytes,1,rep,name=AllUser,json=allUser" json:"AllUser,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserList) Reset()                    { *m = UserList{} }
func (m *UserList) String() string            { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()               {}
func (*UserList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserList) GetAllUser() []*User {
	if m != nil {
		return m.AllUser
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "users.User")
	proto.RegisterType((*UserId)(nil), "users.UserId")
	proto.RegisterType((*Void)(nil), "users.Void")
	proto.RegisterType((*UserList)(nil), "users.UserList")
}

func init() { proto.RegisterFile("proto/user/users.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0xd7, 0xf4, 0xdf, 0x76, 0x8b, 0x0a, 0x17, 0x19, 0x61, 0xf8, 0x10, 0x02, 0x62, 0x5f,
	0x9c, 0xb8, 0x6f, 0xe0, 0xe3, 0x40, 0x7c, 0x28, 0xe8, 0xab, 0x14, 0x13, 0xdb, 0xc0, 0x66, 0x47,
	0x92, 0x3d, 0xf8, 0x2d, 0xfc, 0xc8, 0x92, 0xdb, 0x94, 0xf5, 0xa5, 0xbd, 0xbf, 0x73, 0xce, 0x0d,
	0xe7, 0xc2, 0xfa, 0x64, 0x07, 0x3f, 0x3c, 0x9d, 0x9d, 0xb6, 0xf4, 0x71, 0x5b, 0x12, 0x30, 0x27,
	0x90, 0x7f, 0x09, 0x64, 0xef, 0x4e, 0x5b, 0xbc, 0x06, 0x66, 0x14, 0x4f, 0x04, 0xab, 0xd3, 0x86,
	0x19, 0x85, 0x77, 0xb0, 0xfa, 0x36, 0xd6, 0xf9, 0xb7, 0xf6, 0xa8, 0x39, 0x13, 0xac, 0x5e, 0x35,
	0x17, 0x01, 0x11, 0xb2, 0x2f, 0xe3, 0x7f, 0x79, 0x4a, 0x06, 0xcd, 0x78, 0x0b, 0xf9, 0xa9, 0x1f,
	0x7e, 0x34, 0xcf, 0x48, 0x1c, 0x01, 0xd7, 0x50, 0xf4, 0xda, 0x74, 0xbd, 0xe7, 0x39, 0xc9, 0x91,
	0x90, 0x43, 0x79, 0x6c, 0xad, 0x35, 0x5a, 0xf1, 0x42, 0xb0, 0x7a, 0xd9, 0x4c, 0x28, 0x05, 0x14,
	0xa1, 0xd1, 0x5e, 0x85, 0xdd, 0x33, 0x4d, 0xb1, 0x57, 0x24, 0x59, 0x40, 0xf6, 0x31, 0x18, 0x25,
	0x9f, 0x61, 0x19, 0x92, 0xaf, 0xc6, 0x79, 0xbc, 0x87, 0xf2, 0xe5, 0x70, 0x08, 0xc8, 0x13, 0x91,
	0xd6, 0xd5, 0xae, 0xda, 0x8e, 0xe7, 0x06, 0xa9, 0x29, 0xdb, 0xd1, 0xdb, 0x7d, 0x42, 0x1e, 0xfe,
	0x0e, 0x1f, 0xa0, 0xec, 0xb4, 0xa7, 0xd3, 0xaf, 0x66, 0xc9, 0xbd, 0xda, 0xcc, 0x17, 0xe5, 0x02,
	0x1f, 0xa1, 0xea, 0xb4, 0x8f, 0x6f, 0x3b, 0x9c, 0xdc, 0x50, 0x60, 0x73, 0x33, 0x8b, 0x86, 0x16,
	0x72, 0xf1, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x57, 0xe9, 0xa8, 0x70, 0x01, 0x00, 0x00,
}
